service: dynamodb-serverless-crud-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.productsTableName}

custom:
  productsTableName: products-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getProduct:
    handler: api.getProduct
    name: get-product
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: product/{productId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resources: !GetAtt ProductsTable.Arn
  createProduct:
    handler: api.createProduct
    name: create-product
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: product
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resources: !GetAtt ProductsTable.Arn
  updateProduct:
    handler: api.updateProduct
    name: update-product
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: product/{productId}
          method: PATCH
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resources: !GetAtt ProductsTable.Arn
  deleteProduct:
    handler: api.deleteProduct
    name: delete-product
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: product/{productId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dybnamodb:DeleteItem"
        Resources: !GetAtt ProductsTable.Arn
  getAllProducts:
    handler: api.getAllProducts
    name: get-all-products
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: products
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resources: !GetAtt ProductsTable.Arn

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsTableName}
        AttributeDefinitions:
          - AttributeName: productId
            Attributetype: S
        KeySehema:
          - AttributeName: productId
            KeyType: HASH
        ProvisioedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
